---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: sample.docker.internal
      http:
        paths:
          - backend:
              service:
                name: sample-service
                port:
                  number: 80
